import assert from 'node:assert/strict';
import { chromium } from '@playwright/test';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { initStore } from '../src/storage.js';
import { saveItem, saveSources } from '../src/storage.js';
import { startDashboard } from '../src/dashboard.js';
import { createManualItem } from '../src/adapters/manual.js';
import { makeSource } from '../src/models.js';

const root=await mkdtemp(join(tmpdir(),'intake-browser-'));
let browser, dashboard;
try {
 await initStore(root);
 const source=makeSource('manual',{id:'manual',name:'Manual'});
 await saveSources(root,[source]);
 const item=await createManualItem(root,source,{title:'Browser polish check',body:'Please verify the local operator workflow.'});
 await saveItem(root,item);
 dashboard=await startDashboard(root,{port:0,token:'browser-regression-original-token'});
 browser=await chromium.launch({headless:true});
 const page=await browser.newPage();
 const errors=[];page.on('pageerror',error=>errors.push(error.message));
 await page.goto(dashboard.url);
 await page.getByRole('heading',{name:'Reply & actions'}).waitFor();
 await page.getByRole('button',{name:'Browser polish check'}).click();
 await page.getByRole('button',{name:'Assign to me'}).click();
 await page.getByRole('button',{name:'Unassign',exact:true}).waitFor();
 await page.keyboard.press('s');
 await page.locator('#queues').getByRole('button',{name:/^Later 1$/}).click();
 await page.getByRole('button',{name:'Browser polish check'}).waitFor();
 await page.keyboard.press('ControlOrMeta+K');
 await page.getByRole('dialog',{name:'Quick commands'}).waitFor();
 await page.getByRole('button',{name:/Go to Inbox/}).click();
 await page.getByRole('button',{name:'Settings',exact:true}).click();
 await page.getByText('Advanced settings',{exact:true}).click();
 const [rotated]=await Promise.all([page.waitForResponse(response=>response.url().endsWith('/api/dashboard-token/rotate')),page.getByRole('button',{name:'Rotate token',exact:true}).click()]);
 assert.equal(rotated.status(),200);
 await page.waitForFunction(()=>sessionStorage.getItem('intakeToken') && sessionStorage.getItem('intakeToken')!=='browser-regression-original-token');
 assert.equal(new URL(page.url()).searchParams.has('token'),false);
 const token=await page.evaluate(()=>sessionStorage.getItem('intakeToken'));
 const base=new URL(dashboard.url).origin;
 assert.equal((await fetch(`${base}/api/settings`,{headers:{'x-intake-token':'browser-regression-original-token'}})).status,401);
 assert.equal((await fetch(`${base}/api/settings`,{headers:{'x-intake-token':token}})).status,200);
 const [saved]=await Promise.all([page.waitForResponse(response=>response.url().endsWith('/api/settings/update')),page.getByRole('button',{name:'Save settings',exact:true}).click()]);
 assert.equal(saved.status(),200);
 await page.reload();
 await page.getByRole('button',{name:'Settings',exact:true}).click();
 await page.getByText('Advanced settings',{exact:true}).click();
 await page.getByRole('button',{name:'Rotate token',exact:true}).waitFor();
 await page.setViewportSize({width:390,height:844});
 await page.getByRole('button',{name:'Inbox views'}).click();
 await page.locator('aside').waitFor({state:'visible'});
 assert.deepEqual(errors,[]);
 console.log('PASS Chromium: inbox ownership/snooze, command palette, advanced settings, mobile navigation, token rotation, URL scrub, no page errors');
}finally{
 await browser?.close();
 if(dashboard)await new Promise(resolve=>dashboard.server.close(resolve));
 await rm(root,{recursive:true,force:true});
}
